project:
  name : "Manual_MLOps_Challenge"
  author: "Shlok Shetty"

data:
  raw_path: "data/raw/dataset_raw.csv"
  processed_dir: "data/processed"
  production_dir : "data/production"
  version : "v3"

data_split:
  train_size: 7000

model:
  version: "v6"
  algorithm: "RandomForest"
  n_estimators: 100
  max_depth: 40
  random_state: 42



deployment:
  threshold: 0.5 #model threshold for prtedicting 0/1
  port: 8000
  active_model_version : "v6"

monitoring:
  error_threshold: 0.075
  recall_drop_threshold: 0.15
